CREATE TABLE Contact(
Id INT NOT NULL IDENTITY(1, 1),
Name NVARCHAR(30),
Age INT,
Email NVARCHAR(30),
BirthDate DATETIMEOFFSET(7),
Weight FLOAT,
MaritalStatus INT
)ON[PRIMARY]
GO
SET IDENTITY_INSERT dbo.Contact ON
GO